/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface HandleTokenURIInterface extends utils.Interface {
  functions: {
    "getTokenURI(uint256,string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getTokenURI",
    values: [BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getTokenURI",
    data: BytesLike
  ): Result;

  events: {};
}

export interface HandleTokenURI extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: HandleTokenURIInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getTokenURI(
      tokenId: BigNumberish,
      localName: string,
      namespace: string,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  getTokenURI(
    tokenId: BigNumberish,
    localName: string,
    namespace: string,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    getTokenURI(
      tokenId: BigNumberish,
      localName: string,
      namespace: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getTokenURI(
      tokenId: BigNumberish,
      localName: string,
      namespace: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getTokenURI(
      tokenId: BigNumberish,
      localName: string,
      namespace: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
