/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ProfileTokenURIInterface extends utils.Interface {
  functions: {
    "blockSeed()": FunctionFragment;
    "getTokenURI(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "blockSeed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTokenURI",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "blockSeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenURI",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ProfileTokenURI extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ProfileTokenURIInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    blockSeed(overrides?: CallOverrides): Promise<[string]>;

    getTokenURI(
      profileId: BigNumberish,
      mintTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  blockSeed(overrides?: CallOverrides): Promise<string>;

  getTokenURI(
    profileId: BigNumberish,
    mintTimestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    blockSeed(overrides?: CallOverrides): Promise<string>;

    getTokenURI(
      profileId: BigNumberish,
      mintTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    blockSeed(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenURI(
      profileId: BigNumberish,
      mintTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    blockSeed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTokenURI(
      profileId: BigNumberish,
      mintTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
